---
- name: sleep alot
  hosts: 54.219.167.216
  become: yes 
  become_user: Administrator
  vars_files:
    - vault/secrets.yml
    - vault/win_connect.yml
  tasks:
  - name: Run ps1
    script: ./scripts/sleep.ps1

  - name: copyscript
    win_copy:
      src: /scripts/sleep.ps1
      dest: c:\Temp